### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by ngaspar** [Jjagg/DragonBonesMG#2]
Shouldn't submit this as an issue, but I couldn't find any reference anywhere: what sort of licensing/permissions are you releasing this code under?

**Comment by Jjagg** [comment]
Ah, sorry. I forgot to add a license back then.
I just added one (public domain).

Note that I never fully developed this lib and I don't recommend using it for production games. Also, DragonBones have developed an official C# runtime: https://github.com/DragonBones/DragonBonesCSharp
It shouldn't be hard to write a MonoGame back end for it. In fact I think someone on the MG forums managed to get it working.
