### ISSUE TITLE
Anymore updates?

### ISSUE THREAD

**Issue by mackcoding** [Jjagg/DragonBonesMG#3]
Hi! I've been messing with DragonBones and now DragonBonesMG. I'm sad to see there has been no updates in 2 years. I'm also surprised more people aren't using DragonBones. 

It looks like this code is using DragonBones 4.0 file format. I can't get it to run on the latest version of Monogame either. 

Is there planned updates to get this project up-to-date (or a real alternative) or should I look at rewriting it myself?

Thanks!

**Comment by Jjagg** [comment]
Hey there! Sorry for the late response, I'm on holiday :D I haven't continued working on this because there is an official C# runtime for DragonBones. Check it out here: https://github.com/DragonBones/DragonBonesCSharp

**Comment by Jjagg** [comment]
I've edited the readme to link to the official runtime! Hope it works out for you :)
